--- #YAML:1.0
name:               Pod-WordML
version:            0.14
abstract:           Convert Pod to Microsoft's WordML format
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Pod::Escapes:      0
    Pod::PseudoPod:    0
    Test::LongString:  0
    Tie::Cycle:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
